### ISSUE TITLE
nuget package restore repeatedly

### ISSUE THREAD

**Issue by ylka** [WeihanLi/WeihanLi.EntityFramework#36]
after open the project, the nuget restore repeatedly.

![WeChat Photo Editor_20200622174728](https://user-images.githubusercontent.com/8136405/85273643-6fbb2180-b4b0-11ea-980c-bdab29cd6668.jpg)

**Comment by WeihanLi** [comment]
seemed to be some bug with vs(package manager)

recommend to use `dotnet restore` or `dotnet build` to restore the dependencies

you can also run the build script on the project root dir (`build.ps1` for windows and `build.sh` for linux or mac)

**Comment by ylka** [comment]
:disappointed_relieved:
the bug is annoying, thanks!

**Comment by WeihanLi** [comment]
uncheck the features below, restore packages manually may help

![image](https://user-images.githubusercontent.com/7604648/85302621-fc2f0980-b4db-11ea-9885-9e71f343623e.png)

**Comment by ylka** [comment]
1 I rename the Directory.Build.props in root directory, stop restore;
2 modify Directory.Build.props, when comment `<Import Project="./build/version.props" />`, stop restore;
3 the key is 
```
<VersionSuffix Condition="'$(Configuration)'=='DEBUG'">preview-$([System.DateTime]::Now.ToString("yyyyMMdd-HHmmss"))</VersionSuffix>
```
if set `ss`, it restore every second.

**Comment by WeihanLi** [comment]
Thanks for report that and your solution, the `version.props` had been updated
